from enum import IntEnum, StrEnum


class ErrorCodes(IntEnum):
    UNKNOWN = 999


class EnitityStatuses(StrEnum):
    CREATING = "CREATING"
    ACTIVE = "ACTIVE"
    FAILED = "FAILED"
    DELETING = "DELETING"
    SERVICE = "SERVICE"
    PARTIAL = "PARTIAL"
    BAD_AUTH = "BAD_AUTH"
    RESERVED = "RESERVED"


class PoolTypes(StrEnum):
    AUTOMATED = "AUTOMATED"
    STATIC = "STATIC"
    GUEST = "GUEST"
    RDS = "RDS"
    APPLICATION = "APPLICATION"
    PHYS = "PHYS"


class OSTypes(StrEnum):
    WINDOWS = "Windows"
    LINUX = "Linux"
    OTHER = "Other"


class ConnectionTypes(StrEnum):
    RDP = "RDP"
    NATIVE_RDP = "NATIVE_RDP"
    GLINT = "GLINT"


class PermissionTypes(StrEnum):
    USB_REDIR = "USB_REDIR"
    FOLDERS_REDIR = "FOLDERS_REDIR"
    SHARED_CLIPBOARD_CLIENT_TO_GUEST = "SHARED_CLIPBOARD_CLIENT_TO_GUEST"
    SHARED_CLIPBOARD_GUEST_TO_CLIENT = "SHARED_CLIPBOARD_GUEST_TO_CLIENT"
    PRINTERS_REDIR = "PRINTERS_REDIR"
    DRAG_AND_DROP_FILES = "DRAG_AND_DROP_FILES"
    VM_POWER_CONTROL = "VM_POWER_CONTROL"
